version: '3.8'

services:
  app:
    build: .
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/kayla-business
      - PORT=9000
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./mongo-backup:/dump

volumes:
  mongo-data:
